//Source code generated by AppGPT (www.appgpt.tech)
//to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from 'typeorm';

@Entity('Beds')
export class BedsEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column('text', { nullable: true })
  bedID: string;

  @Column('text', { nullable: true })
  status: string;

  @Column('text', { nullable: true })
  type: string;

  @Column('integer', { nullable: true })
  hospitalID: number;
}
