//Source code generated by AppGPT (www.appgpt.tech)
//to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from 'typeorm';

@Entity('Hospitals')
export class HospitalsEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column('text', { nullable: true })
  name: string;

  @Column('text', { nullable: true })
  location: string;

  @Column('integer', { nullable: true })
  totalBeds: number;

  @Column('integer', { nullable: true })
  availableBeds: number;
}
