//Source code generated by AppGPT (www.appgpt.tech)
//to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from 'typeorm';

@Entity('Users')
export class UsersEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column('text', { nullable: true })
  userID: string;

  @Column('text', { nullable: true })
  name: string;

  @Column('text', { nullable: true })
  contactInformation: string;

  @Column('text', { nullable: true })
  medicalHistory: string;

  @Column('integer', { nullable: true })
  preferredHospital: number;
}
